-- Background Jobs: business state for async tasks.
-- pgmq handles message delivery; this table handles product-visible status.

-- Status enum
CREATE TYPE public.background_job_status AS ENUM (
  'queued',
  'running',
  'succeeded',
  'failed',
  'canceled',
  'dead_letter'
);

-- Job type enum (extensible)
CREATE TYPE public.background_job_type AS ENUM (
  'image_generation'
);

-- Main table
CREATE TABLE public.background_jobs (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id  uuid NOT NULL REFERENCES public.workspaces(id),
  project_id    uuid REFERENCES public.projects(id) ON DELETE SET NULL,
  canvas_id     uuid REFERENCES public.canvases(id) ON DELETE SET NULL,
  session_id    uuid REFERENCES public.chat_sessions(id) ON DELETE SET NULL,
  thread_id     text,

  queue_name    text NOT NULL,
  job_type      public.background_job_type NOT NULL,
  status        public.background_job_status NOT NULL DEFAULT 'queued',

  payload       jsonb NOT NULL DEFAULT '{}',
  result        jsonb,
  error_code    text,
  error_message text,

  attempt_count integer NOT NULL DEFAULT 0,
  max_attempts  integer NOT NULL DEFAULT 3,

  created_by    uuid NOT NULL REFERENCES public.app_users(id),
  created_at    timestamptz NOT NULL DEFAULT now(),
  started_at    timestamptz,
  completed_at  timestamptz,
  failed_at     timestamptz,
  canceled_at   timestamptz
);

-- Indexes
CREATE INDEX idx_background_jobs_status ON public.background_jobs(status);
CREATE INDEX idx_background_jobs_workspace ON public.background_jobs(workspace_id);
CREATE INDEX idx_background_jobs_created_by ON public.background_jobs(created_by);
CREATE INDEX idx_background_jobs_job_type_status ON public.background_jobs(job_type, status);

-- updated_at trigger
ALTER TABLE public.background_jobs ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
CREATE TRIGGER trg_background_jobs_updated_at
  BEFORE UPDATE ON public.background_jobs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS: users see their own jobs
ALTER TABLE public.background_jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY background_jobs_user_policy
  ON public.background_jobs FOR ALL
  USING (private.current_user_id() = created_by);

-- Service role bypass for worker process
CREATE POLICY background_jobs_service_role
  ON public.background_jobs FOR ALL
  TO service_role
  USING (true) WITH CHECK (true);

-- Queue backend.
-- Prefer the pgmq extension when it is installed. For local PostgreSQL
-- installs without pgmq, provide a small compatibility layer with the subset
-- of functions used by the server and worker.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_available_extensions
    WHERE name = 'pgmq'
  ) THEN
    CREATE EXTENSION IF NOT EXISTS pgmq;
  ELSE
    CREATE SCHEMA IF NOT EXISTS pgmq;

    CREATE TABLE IF NOT EXISTS pgmq.local_messages (
      queue_name text NOT NULL,
      msg_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      read_ct integer NOT NULL DEFAULT 0,
      enqueued_at timestamptz NOT NULL DEFAULT now(),
      vt timestamptz NOT NULL DEFAULT now(),
      message jsonb NOT NULL,
      archived_at timestamptz,
      deleted_at timestamptz
    );

    CREATE INDEX IF NOT EXISTS local_messages_available_idx
      ON pgmq.local_messages(queue_name, vt, msg_id)
      WHERE archived_at IS NULL AND deleted_at IS NULL;

    EXECUTE $fn$
      CREATE OR REPLACE FUNCTION pgmq.create(p_queue text)
      RETURNS void
      LANGUAGE sql
      AS $body$
        SELECT NULL::void;
      $body$;
    $fn$;

    EXECUTE $fn$
      CREATE OR REPLACE FUNCTION pgmq.send(
        p_queue text,
        p_message jsonb,
        p_delay integer DEFAULT 0
      )
      RETURNS bigint
      LANGUAGE sql
      AS $body$
        INSERT INTO pgmq.local_messages (queue_name, message, vt)
        VALUES (
          p_queue,
          p_message,
          now() + make_interval(secs => greatest(p_delay, 0))
        )
        RETURNING msg_id;
      $body$;
    $fn$;

    EXECUTE $fn$
      CREATE OR REPLACE FUNCTION pgmq.read(
        p_queue text,
        p_vt integer,
        p_qty integer
      )
      RETURNS TABLE (
        msg_id bigint,
        read_ct integer,
        enqueued_at timestamptz,
        vt timestamptz,
        message jsonb
      )
      LANGUAGE sql
      AS $body$
        WITH claimed AS (
          SELECT m.msg_id
          FROM pgmq.local_messages AS m
          WHERE m.queue_name = p_queue
            AND m.archived_at IS NULL
            AND m.deleted_at IS NULL
            AND m.vt <= now()
          ORDER BY m.msg_id
          LIMIT greatest(p_qty, 0)
          FOR UPDATE SKIP LOCKED
        )
        UPDATE pgmq.local_messages AS m
        SET read_ct = m.read_ct + 1,
            vt = now() + make_interval(secs => greatest(p_vt, 0))
        FROM claimed
        WHERE m.msg_id = claimed.msg_id
        RETURNING m.msg_id, m.read_ct, m.enqueued_at, m.vt, m.message;
      $body$;
    $fn$;

    EXECUTE $fn$
      CREATE OR REPLACE FUNCTION pgmq.read_with_poll(
        p_queue text,
        p_vt integer,
        p_qty integer,
        p_max_poll_seconds integer DEFAULT 5,
        p_poll_interval_ms integer DEFAULT 500
      )
      RETURNS TABLE (
        msg_id bigint,
        read_ct integer,
        enqueued_at timestamptz,
        vt timestamptz,
        message jsonb
      )
      LANGUAGE sql
      AS $body$
        SELECT *
        FROM pgmq.read(p_queue, p_vt, p_qty);
      $body$;
    $fn$;

    EXECUTE $fn$
      CREATE OR REPLACE FUNCTION pgmq.delete(p_queue text, p_msg_id bigint)
      RETURNS boolean
      LANGUAGE sql
      AS $body$
        UPDATE pgmq.local_messages
        SET deleted_at = now()
        WHERE queue_name = p_queue
          AND msg_id = p_msg_id
          AND deleted_at IS NULL
        RETURNING true;
      $body$;
    $fn$;

    EXECUTE $fn$
      CREATE OR REPLACE FUNCTION pgmq.archive(p_queue text, p_msg_id bigint)
      RETURNS boolean
      LANGUAGE sql
      AS $body$
        UPDATE pgmq.local_messages
        SET archived_at = now()
        WHERE queue_name = p_queue
          AND msg_id = p_msg_id
          AND archived_at IS NULL
        RETURNING true;
      $body$;
    $fn$;

    EXECUTE $fn$
      CREATE OR REPLACE FUNCTION pgmq.set_vt(
        p_queue text,
        p_msg_id bigint,
        p_vt integer
      )
      RETURNS void
      LANGUAGE sql
      AS $body$
        UPDATE pgmq.local_messages
        SET vt = now() + make_interval(secs => greatest(p_vt, 0))
        WHERE queue_name = p_queue
          AND msg_id = p_msg_id;
      $body$;
    $fn$;
  END IF;
END
$$;

-- Create pgmq queue (idempotent — extension or local compatibility layer).
SELECT pgmq.create('image_generation_jobs');
